baseURL = 'https://diohabara.github.io'
defaultContentLanguage = "en"
languageCode = 'en'
theme = 'gokarna'
title = 'barabara diary'

# Automatically generate robots.txt
enableRobotsTXT = true

[markup]
# ref: https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
# ref: https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4

[params]
avatarURL = "/images/avatar.jpg"
description = "MAKE THE WORLD FUN AGAIN"
showPostsOnHomePage = "recent"
# Keywords relevant for SEO
metaKeywords = ["blog", "diohabara", "hugo"]

[menu]
[[menu.main]]
identifier = "blog"
name = "blog"
post = ""
pre = "<span data-feather='globe'></span>"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "github"
url = "https://github.com/diohabara/"
weight = 4
# We use feather-icons: https://feathericons.com/
pre = "<span data-feather='github'></span>"

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/index.xml"
weight = 5
