# The base URL of the site; the only required configuration variable.
base_url = "https://diohabara.netlify.app/"
description = "Blog by (^_^)"

theme = "even"
highlight_code = true
highlight_theme = "kronuz"
generate_rss = true
taxonomies = [
    {name = "tags", rss = true},
]
compile_sass = true
build_search_index = true

[extra]
even_title = "Unit Karma"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/works", name = "Works"},
    {url = "$BASE_URL/tags", name = "Tags"},
]
katex_enable = true
katex_auto_render = true