baseURL = 'https://diohabara.github.io'
languageCode = 'ja'
theme = 'gokarna'
title = 'barabara diary'

# Automatically generate robots.txt
enableRobotsTXT = true

[markup]
# ref: https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
# ref: https://gohugo.io/getting-started/configuration-markup/#highlight
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4

[params]
avatarURL = "/images/avatar.jpg"
description = "MAKE THE WORLD FUN AGAIN"
showPostsOnHomePage = "recent"
# Keywords relevant for SEO
metaKeywords = ["blog", "diohabara", "hugo"]
# Default OGP image
images = ["/images/avatar.jpg"]


# Menu configuration for English
[menu]
# feather-icons でアイコン設定可能: https://feathericons.com/
[[menu.main]]
identifier = "blog"
name = "blog"
post = ""
pre = "<span data-feather='globe'></span>"
url = "/blog/"
weight = 2

[[menu.main]]
identifier = "compensation"
name = "Compensation"
pre = "<span data-feather='dollar-sign'></span>"
url = "/compensation/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
pre = "<span data-feather='tag'></span>"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "github"
pre = "<span data-feather='github'></span>"
url = "https://github.com/diohabara/"
weight = 4

[[menu.main]]
identifier = "rss"
pre = "<span data-feather='rss'></span>"
url = "/index.xml"
weight = 5
