# Trigger the workflow on push or pull request
on: [push, pull_request]

name: Test
jobs:
  test:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Shellcheck
        uses: docker://koalaman/shellcheck:latest
        with:
          args: ./entrypoint.sh
